const services = [
  ["CN", "Nhập khẩu chính ngạch Trung Quốc", "Đồng hành từ tìm nguồn, đàm phán, hợp đồng đến khai báo hải quan và giao hàng tận nơi."],
  ["01", "Vận chuyển quốc tế & Việt Nam", "Giải pháp đường bộ, đường biển và đường hàng không phù hợp từng loại hàng, thời gian và ngân sách."],
  ["02", "Khai báo hải quan", "Kiểm tra mã HS, thuế, hồ sơ chuyên ngành và xử lý thủ tục minh bạch, đúng quy định."],
  ["03", "Kho bãi & phân phối", "Nhận hàng, kiểm đếm, lưu kho, đóng gói và phân phối linh hoạt đến điểm bán trên toàn quốc."],
];
const process = [["01","Tiếp nhận yêu cầu","Xác định mặt hàng, sản lượng, tiến độ và điều kiện giao nhận."],["02","Tư vấn & báo giá","Đề xuất phương án tối ưu, chi phí rõ ràng, hạn chế phát sinh."],["03","Thực hiện thủ tục","Kiểm tra chứng từ, khai báo hải quan và theo sát lịch trình."],["04","Giao hàng & đối soát","Giao đúng địa điểm, cập nhật đầy đủ và hoàn thiện hồ sơ."]];
const news = [["Cẩm nang","12.08.2025","5 lưu ý khi nhập khẩu chính ngạch hàng hóa từ Trung Quốc","cargo"],["Thị trường","04.08.2026","Tối ưu chi phí logistics trong mùa cao điểm cuối năm","port"],["Hoạt động","25.07.2026","Nam Anh mở rộng mạng lưới đối tác vận tải xuyên biên giới","map"]];
function Arrow(){return <span aria-hidden="true">↗</span>}

export default function Home(){return <main>
  <div className="topbar"><div className="container topbar-inner"><span>Hotline: <a href="tel:19000000">1900 0000</a></span><span>Email: <a href="hungnguyen@namanh.asia">admin@namanh.asia</a></span></div></div>
  <header className="header"><div className="container nav-wrap">
    <a className="brand" href="#trang-chu" aria-label="Nam Anh - Trang chủ"><img className="brand-logo" src="/favicon.svg" alt="Logo Nam Anh"/><span><strong>NAM ANH</strong><small>Logistics</small></span></a>
    <nav className="desktop-nav" aria-label="Điều hướng chính"><a href="#trang-chu">Trang chủ</a><a href="#gioi-thieu">Giới thiệu</a><a href="#dich-vu">Dịch vụ</a><a href="#nhap-khau">Nhập khẩu</a><a href="#logistics">Vận chuyển</a><a href="#tin-tuc">Tin tức</a><a href="#lien-he">Liên hệ</a></nav>
    <a className="oms-button" href="https://oms.namanh.asia" target="_blank" rel="noreferrer">Đăng nhập OMS <Arrow/></a>
    <details className="mobile-menu"><summary aria-label="Mở menu">☰</summary><div><a href="#gioi-thieu">Giới thiệu</a><a href="#dich-vu">Dịch vụ</a><a href="#nhap-khau">Nhập khẩu</a><a href="#logistics">Logistics</a><a href="#tin-tuc">Tin tức</a><a href="#lien-he">Liên hệ</a><a href="https://oms.namanh.asia">Đăng nhập OMS</a></div></details>
  </div></header>
  <section id="trang-chu" className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-content"><div className="eyebrow light"><span/> Đối tác Logistics tin cậy</div><h1>Kết nối thương mại.<br/><em>Vận hành thông suốt.</em></h1><p>Nam Anh cung cấp giải pháp nhập khẩu chính ngạch và logistics trọn gói, giúp doanh nghiệp đưa hàng hóa về Việt Nam an toàn, đúng tiến độ.</p><div className="hero-actions"><a className="primary-button" href="#lien-he">Nhận tư vấn miễn phí <Arrow/></a><a className="text-button" href="#dich-vu">Khám phá dịch vụ <span>↓</span></a></div></div>
    <div className="hero-panel" aria-hidden="true"><div className="route-map"><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/><span className="route r1"/><span className="route r2"/><div className="ship">▰</div></div><div className="floating-stat"><b>Toàn trình</b><span>theo dõi một đầu mối</span></div></div>
    <div className="container hero-metrics"><div><strong>10+</strong><span>Năm kinh nghiệm*</span></div><div><strong>20.500+</strong><span>Lô hàng xử lý*</span></div><div><strong>30+</strong><span>Tỉnh thành kết nối*</span></div><div><strong>24/7</strong><span>Hỗ trợ vận hành</span></div></div>
  </section>
  <section id="gioi-thieu" className="section about"><div className="container two-col"><div className="visual-block warehouse"><div className="visual-label">ẢNH DOANH NGHIỆP<br/><small>Thay tại app/globals.css</small></div><div className="stamp">NAM ANH<br/><b>TRUSTED</b></div></div><div className="content-block"><div className="eyebrow"><span/> Về Nam Anh</div><h2>Đồng hành cùng doanh nghiệp trên mọi hành trình hàng hóa</h2><p className="lead">Công ty Cổ phần Đầu tư và Xuất nhập khẩu Nam Anh hướng đến trở thành đối tác vận hành thương mại đáng tin cậy giữa Việt Nam và Trung Quốc.</p><p>Với đội ngũ am hiểu thị trường, quy trình hải quan và mạng lưới vận tải linh hoạt, chúng tôi thiết kế giải pháp sát nhu cầu thực tế của từng khách hàng — từ lô hàng đầu tiên đến chuỗi cung ứng dài hạn.</p><div className="values"><div><b>Minh bạch</b><span>Chi phí và tiến độ rõ ràng</span></div><div><b>Chủ động</b><span>Cập nhật xuyên suốt hành trình</span></div><div><b>Hiệu quả</b><span>Tối ưu theo từng nhu cầu</span></div></div></div></div></section>
  <section id="dich-vu" className="section services"><div className="container"><div className="section-heading"><div><div className="eyebrow light"><span/> Năng lực cốt lõi</div><h2>Giải pháp toàn diện cho<br/>chuỗi cung ứng của bạn</h2></div><p>Từ cửa nhà cung cấp đến kho của bạn, Nam Anh phối hợp mọi điểm chạm trong một quy trình thống nhất.</p></div><div className="service-grid">{services.map((s,i)=><article className={i===0?"featured":""} key={s[1]}><span className="service-icon">{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><a href="#lien-he">Tìm hiểu thêm <Arrow/></a></article>)}</div></div></section>
  <section id="nhap-khau" className="section import-section"><div className="container two-col reverse-mobile"><div className="content-block"><div className="eyebrow"><span/> Chuyên tuyến Trung Quốc – Việt Nam</div><h2>Nhập khẩu chính ngạch, an tâm từ đầu nguồn</h2><p className="lead">Một đầu mối xuyên suốt giúp bạn kiểm soát tốt hơn chứng từ, thời gian và chi phí.</p><ul className="check-list"><li>Tư vấn điều kiện và chính sách mặt hàng</li><li>Hỗ trợ tìm kiếm, xác minh và làm việc với nhà cung cấp</li><li>Hợp đồng ngoại thương, thanh toán và chứng từ</li><li>Khai báo hải quan, kiểm tra chuyên ngành</li><li>Vận chuyển về kho doanh nghiệp tại Việt Nam</li></ul><a className="dark-button" href="#lien-he">Tư vấn tuyến hàng <Arrow/></a></div><div className="visual-block china-route"><div className="country cn">TRUNG QUỐC<small>Nhà cung cấp</small></div><div className="route-line"><span>→</span><small>CHÍNH NGẠCH</small></div><div className="country vn">VIỆT NAM<small>Kho của bạn</small></div></div></div></section>
  <section id="logistics" className="section process-section"><div className="container"><div className="center-heading"><div className="eyebrow"><span/> Quy trình vận hành</div><h2>Đơn giản hóa logistics trong 4 bước</h2><p>Bạn tập trung vào kinh doanh. Nam Anh phụ trách phần còn lại.</p></div><div className="process-grid">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="logistics-banner"><div><small>GIẢI PHÁP LINH HOẠT</small><h3>Đường bộ · Đường biển · Đường hàng không</h3><p>Lựa chọn phương thức phù hợp nhất với thời gian, loại hàng và ngân sách của bạn.</p></div><a href="#lien-he">Yêu cầu báo giá <Arrow/></a></div></div></section>
  <section id="tin-tuc" className="section news-section"><div className="container"><div className="section-heading dark-text"><div><div className="eyebrow"><span/> Tin tức & kiến thức</div><h2>Cập nhật từ Nam Anh</h2></div><a className="all-link" href="#tin-tuc">Xem tất cả <Arrow/></a></div><div className="news-grid">{news.map(n=><article key={n[2]}><div className={`news-image ${n[3]}`}><span>ẢNH BÀI VIẾT</span></div><div className="news-meta"><span>{n[0]}</span><time>{n[1]}</time></div><h3>{n[2]}</h3><a href="#lien-he">Đọc bài viết <Arrow/></a></article>)}</div></div></section>
  <section id="lien-he" className="contact-section"><div className="container contact-grid"><div><div className="eyebrow light"><span/> Bắt đầu hành trình</div><h2>Bạn có lô hàng cần tư vấn?</h2><p>Để lại thông tin, đội ngũ Nam Anh sẽ liên hệ và đề xuất phương án phù hợp trong thời gian sớm nhất.</p><div className="contact-details"><div><small>HOTLINE</small><a href="tel:19000000">1900 0000</a></div><div><small>EMAIL</small><a href="mailto:hungnguyen@namanh.asia">admin@namanh.asia</a></div><div><small>VĂN PHÒNG</small><span>Toà nhà TMDV Vinfast Phúc Yên, P. Phúc Yên, T. Phú Thọ</span></div></div></div>
    <form className="contact-form" action="mailto:hello@namanh.asia" method="post" encType="text/plain"><h3>Yêu cầu tư vấn</h3><label>Họ và tên<input name="ho-ten" placeholder="Nguyễn Văn A" required/></label><div className="form-row"><label>Số điện thoại<input name="dien-thoai" type="tel" placeholder="0900 000 000" required/></label><label>Email<input name="email" type="email" placeholder="email@congty.vn"/></label></div><label>Nhu cầu<select name="dich-vu" defaultValue=""><option value="" disabled>Chọn dịch vụ quan tâm</option><option>Nhập khẩu chính ngạch Trung Quốc</option><option>Vận chuyển</option><option>Khai báo hải quan</option><option>Kho bãi & phân phối</option></select></label><label>Thông tin lô hàng<textarea name="noi-dung" placeholder="Mặt hàng, số lượng, điểm đi/đến..." rows={3}/></label><button type="submit">Gửi yêu cầu <Arrow/></button><small>* Thông tin trên website đang là nội dung mẫu và cần được cập nhật trước khi công bố.</small></form>
  </div></section>
  <footer><div className="container footer-grid"><div className="footer-brand"><a className="brand light-brand" href="#trang-chu"><img className="brand-logo" src="/favicon.svg" alt="Logo Nam Anh"/><span><strong>NAM ANH</strong><small>Investment & Import Export</small></span></a><p>Giải pháp nhập khẩu chính ngạch và logistics trọn gói cho doanh nghiệp Việt.</p></div><div><h4>Khám phá</h4><a href="#gioi-thieu">Giới thiệu</a><a href="#dich-vu">Dịch vụ</a><a href="#tin-tuc">Tin tức</a></div><div><h4>Dịch vụ</h4><a href="#nhap-khau">Nhập khẩu Trung Quốc</a><a href="#logistics">Logistics & vận chuyển</a><a href="#lien-he">Khai báo hải quan</a></div><div><h4>Kết nối</h4><a href="https://oms.namanh.asia">Hệ thống OMS ↗</a><a href="#">Facebook</a><a href="#">Zalo OA</a></div></div><div className="container footer-bottom"><span>© 2026 Nam Anh JSC. All rights reserved.</span><span>namanh.asia</span></div></footer>
</main>}

